### PR TITLE
Proper support for all 4 arches on Linux :)

### PR DESCRIPTION
**Pull request by Macleykun**
Updated with upstream
Waiting for https://github.com/Macleykun/Provision/actions/runs/3587243704/jobs/6037367116
Then the image on macley/anisette-server should be fully working :)

Need to test this out, but if you want this earlier in, ya can always test it out aswell by following the read me :) (also gonna update that with a restart policy)

### CODE REVIEW

**Comment by Macleykun** [comment]
The only part I can’t fully test is the 32bit none-arm and armv7 (32bit variant aswell?)
Normal arch and aarch64 is easy doable to test (and I believe I already did so that’s good).

**Comment by Macleykun** [comment]
Smth i noticed on my aarch64 pi:
```bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  106M    0  106M    0     0  4082k      0 --:--:--  0:00:26 --:--:-- 2581k
Archive:  applemusic.apk
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of applemusic.apk or
        applemusic.apk.zip, and cannot find applemusic.apk.ZIP, period.
std.file.FileException@/opt/lib/provision/adi.d(119): lib/arm64-v8a/libCoreADI.so: Apple libraries are not installed correctly. Refer to README for instructions.
----------------
??:? [0x5561a179b3]
??:? [0x55619efb2f]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7f9f1c2b8f]
??:? _d_run_main2 [0x7f9f1c297b]
??:? _d_run_main [0x7f9f1c27e3]
??:? [0x7f9ee7777f]
??:? __libc_start_main [0x7f9ee77857]
??:? [0x55619ef72f]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  133M    0  133M    0     0  21.8M      0 --:--:--  0:00:06 --:--:-- 23.3M
Archive:  applemusic.apk
  inflating: lib/arm64-v8a/libCoreADI.so
  inflating: lib/arm64-v8a/libstoreservicescore.so
Machine requires provisioning... done !
```

It seems there's always a chance that when the container is first started to populate the volume, that the download may fail/has a incomplete .zip downloaded.
However a simple start of the container again did fixed it.

They also work which is great to see :) i'll just add one more part to also make it rootless (it's very easy to do :))

**Comment by Macleykun** [comment]
yup it's working now :) tested it on only x86_64
i'll run it also on aarch64 later (takes a long while do compile).

**Comment by Dadoum** [comment]
I am too lazy to squash commit, so if you don't mind, I will probably merge this PR as-is.

**Comment by Macleykun** [comment]
> I am too lazy to squash commit, so if you don't mind, I will probably merge this PR as-is.

sure! just gimmie one moment still, figuring out rootless still

**Comment by Dadoum** [comment]
I mark the PR as draft to prevent merging this PR while it's not ready.

**Comment by Macleykun** [comment]
> I mark the PR as draft to prevent merging this PR while it's not ready.

done :) ready for merge!
last build was the working one, i haven't dabbled to much in rootless and the volume was giving me some deps probs.

Is all good now :)

**Comment by Macleykun** [comment]
image
you can squash and merge very easily btw :)

**Comment by Dadoum** [comment]
oh I forgot to add the end of your username, oopsie, should I correct that ? (because anyway it's appearing as one commit authored by you)

**Comment by Macleykun** [comment]
> oh I forgot to add the end of your username, oopsie, should I correct that ? (because anyway it's appearing as one commit authored by you)

It’s fine don’t worry about it :)

**Pull request merged**
