### PR TITLE
Fix CI/CD workaround (remove armv7)

### PR DESCRIPTION
**Pull request by Macleykun**
For now, this should work :)
i need to find smth to test it on armV7, for some reason it can't install some packages weirdly enough

### CODE REVIEW

**Comment by Macleykun** [comment]
proof: https://github.com/Macleykun/Provision/actions/runs/3535721141/jobs/5934044221
Meanwhile i'll find out the real reason with CI/CD :D

**Comment by Macleykun** [comment]
so it seems that d-lang doesn't support armv7l
```
 > [builder 13/18] RUN curl -fsS https://dlang.org/install.sh | bash -s ldc-1.30.0:
#19 1.536 Unsupported Arch armv7l
```
Therefore, i'm afraid this PR is the best i can offer until D-lang enables that support

**Comment by Dadoum** [comment]
Since the docker is using ubuntu, can't we just use gdc from repos ? (and so avoid use of the dlang script that does not support armv7). I don't know if the D version is high enough, but it's worth to try i guess

**Comment by Dadoum** [comment]
Non-x86 hosts and targets are not supported by dmd compiler. You can only use gdc or ldc. ldc can be built for armv7, however I don't think it's done automatically on their side (their aarch64 compiler is capable of emitting armv7 code stock tho), and the main pro of gdc is that it is built on almost all distros with gcc, and so it can be installed pretty easily

**Comment by Macleykun** [comment]
i think i got it working, waiting for this now:
https://github.com/Macleykun/Provision/blob/main/Dockerfile

also could use debian by using their unstable branch to update cmake to the right version.
now we can support more arche's which is more fun :D

**Comment by Macleykun** [comment]
So the compile and all works, however when i run it, it only says: Machine requires provisioning... done !
But i don't see anything in the browser itself.
See: https://github.com/Macleykun/Provision/actions/runs/3553440034/jobs/5968954305

you have an idea what might have gone wrong? i believe i got all the deps

**Comment by Dadoum** [comment]
Where can I fetch the docker ?

**Comment by Macleykun** [comment]
> Where can I fetch the docker ?

The image is here: macley/anisette-server:latest

**Comment by Dadoum** [comment]
Hey! I saw that you added a lot of commits to your main branch. Is it ready? If so, can you put those on this branch and squash the commits?

**Comment by Macleykun** [comment]
> Hey! I saw that you added a lot of commits to your main branch. Is it ready? If so, can you put those on this branch and squash the commits?

I would love to but the problem is that the container runs and looks like it works.
But when i visit the app on the browser, I don’t see anything.
Could you verify if the app/image works?

if it’s all good, I’ll check tommorow evening to squash the commits :)

**Comment by Macleykun** [comment]
Thx for closing! I’ll check my main branch as that one has afaik the needed fixes for docker (tho I wanna test my work properly tommorow).

**Pull request closed without merging**
