### PR TITLE
It's Comin' Atcha' | Reduce initial image size to 78-87mb + only keep…

### PR DESCRIPTION
**Pull request by Macleykun**
… required lib + cache lib locally for faster and "offline" capability

This PR finishes the work that was done just to build the docker image. No CI/CD or even docs added yet (tm).

If you like to test this out (please do b/c i haven't yet tested against altserver on linux) Use the following steps:

```
git clone https://github.com/Macleykun/Provision.git --recursive
cd Provision
docker build . -t provision_anisette_server
docker run -v lib_cache:/opt/lib/ -p 6969:6969 provision_anisette_server
```

The first time it'll just download the libs and all, but if you restart the container it won't!
This will also keep happening if you re-build the image. To remove this ability simply don't add the -v part of the run command.

This PR can be merged btw ;).

Futher stuff:
GitHub artefacts per commit (i'm just gonna focus on anisette)
CI/CD to dockerhub (i'm gonna assume this is what you prefer, unless you wish to use the GitHub registery). I'll just keep it at releasing to latest to keep it simple :).

Once the above is done, i'll setup two instances for public use for anyone, i will set the stdout to /dev/null so i won't ever log anything. It'll be hosted on best effort and can just be restarted withoud notice (tho this won't happen often). I do expect people to just host their own instance now as the 4 steps will be condenced into just one command once we have the docker image in dockerhub.

### CODE REVIEW

**Comment by Macleykun** [comment]
If you wish to speed up the download process planned here: https://github.com/Dadoum/Provision/issues/19
Just edit the docker-entrypoint.sh script to download as so.

**Comment by Macleykun** [comment]
I also just added the CD for dockerhub (or github if you want).
So before merging, please choose if you want to publish to dockerhub and/or github registery.
Create the repo in dockerhub/or the other steps for in github to publish the image.
Set the secrets in this repo so the workflow can actually publish to the given registery's.

How it will work in practise: https://github.com/mklements/OLED_Stats_Docker/actions/runs/3222433740/jobs/5271582186
How to do configure everything on your end: https://www.youtube.com/watch?v=HwATG0ygxzU

If you have any questions, feel free to ask :) This should be the last part i can do to give you docker support!
(if you wish to make static versions, i suggest to manually build the image with a tag and publish that to the registery yourself, or edit the workflow just for one commit.

**Comment by Macleykun** [comment]
Tested both 64bit aswell as arch64!
No clue if 32BIT and armv7 (or even 6?) is supported however :)

**Comment by Dadoum** [comment]
Sorry I can't try it right now (I am pretty busy currently) but it can't work on 32 bit since anisette_server cannot be built for 32 bits machines (the server library is incompatible).

**Comment by martadinata666** [comment]
May i suggest?
* Download lib in build stage, let github do the hardwork, and as the README said, only `libstoreservicescore.so` and `libCoreADI.so` needed, we can only extract that.
```
#!/bin/bash

if [ ! -d "lib/" ]; then
  curl https://apps.mzstatic.com/content/android-apple-music-apk/applemusic.apk -O
  if [ "$(uname -m)" = 'aarch64' ]; then
    unzip applemusic.apk "lib/arm64-v8a/libstoreservicescore.so";
    unzip applemusic.apk "lib/arm64-v8a/libCoreADI.so"
  elif [[ "$(uname -m)" = 'arm'* ]]; then
    unzip applemusic.apk "lib/armeabi-v7a/libstoreservicescore.so";
    unzip applemusic.apk "lib/armeabi-v7a/libCoreADI.so";
  elif [ "$(uname -m)" = 'x86_64' ]; then
    unzip applemusic.apk "lib/x86_64/libstoreservicescore.so";
    unzip applemusic.apk "lib/x86_64/libCoreADI.so";
  elif [ "$(uname -m)" = 'i686' ]; then
    unzip applemusic.apk "lib/x86/libstoreservicescore.so";
    unzip applemusic.apk "lib/x86/libCoreADI.so";
  fi
  rm applemusic.apk
fi
```

* Because we download the lib on build stage, on runtime stage we can remove curl and unzip. Lastly we remove the `docker-entrypoint.sh`, just run the `anisette_server`.

**Comment by JJTech0130** [comment]
> Because we download the lib on build stage, on runtime stage we can remove curl and unzip. Lastly we remove the docker-entrypoint.sh, just run the anisette_server.

See, the problem is with licensing. Originally, we had it as you suggest, in the build stage. However, the Apple licensing forbids *distributing* the .so files. If they were contained in the docker image, we would be distributing them. Because they’re fetched at runtime, there is no distribution

**Comment by martadinata666** [comment]
license issues, yah nothing we can do. Sorry for my ignorance.

**Comment by Macleykun** [comment]
> Sorry I can't try it right now (I am pretty busy currently) but it can't work on 32 bit since anisette_server cannot be built for 32 bits machines (the server library is incompatible).

you mean the applemusic lib they provide..?
lib/x86/libCoreADI.so
lib/x86/libstoreservicescore.so


> May i suggest?
> 
> * Download lib in build stage, let github do the hardwork, and as the README said, only `libstoreservicescore.so` and `libCoreADI.so` needed, we can only extract that.
> 
> ```
> #!/bin/bash
> 
> if [ ! -d "lib/" ]; then
>   curl https://apps.mzstatic.com/content/android-apple-music-apk/applemusic.apk -O
>   if [ "$(uname -m)" = 'aarch64' ]; then
>     unzip applemusic.apk "lib/arm64-v8a/libstoreservicescore.so";
>     unzip applemusic.apk "lib/arm64-v8a/libCoreADI.so"
>   elif [[ "$(uname -m)" = 'arm'* ]]; then
>     unzip applemusic.apk "lib/armeabi-v7a/libstoreservicescore.so";
>     unzip applemusic.apk "lib/armeabi-v7a/libCoreADI.so";
>   elif [ "$(uname -m)" = 'x86_64' ]; then
>     unzip applemusic.apk "lib/x86_64/libstoreservicescore.so";
>     unzip applemusic.apk "lib/x86_64/libCoreADI.so";
>   elif [ "$(uname -m)" = 'i686' ]; then
>     unzip applemusic.apk "lib/x86/libstoreservicescore.so";
>     unzip applemusic.apk "lib/x86/libCoreADI.so";
>   fi
>   rm applemusic.apk
> fi
> ```
> 
> * Because we download the lib on build stage, on runtime stage we can remove curl and unzip. Lastly we remove the `docker-entrypoint.sh`, just run the `anisette_server`.

Thank for the suggestion tho! The unzipping is now instant and the runtime size is even smaller now :)
I'm not sure why you added the `;` but i've tested the command it works well :)

Also funny seeing you here from the pi-hosted :D

**Comment by Macleykun** [comment]
Not sure why, but using the volume command somehow makes the container not work.
Need to investigate why, everything else looks good so i might be doing something wrong in a silly way (probably the path i think, will get to this tommorow)
don't merge yet ples

**Comment by martadinata666** [comment]
the `;` jus programming hbits i guess 🤣 
Its the checking issue with the entrypoints. it checks `if it exist`, not `if it empty`.

So when the docker image doesn't have `/opt/lib` it will work, but when mounted with volumes `/opt/lib` already exists from beginning. Then right way is check `if /opt/lib/ empty?`

**Comment by Macleykun** [comment]
> > Also funny seeing you here from the pi-hosted :D
> 
> Just curious what are you working on, and suddenly landing here, it just interesting to see how docker image builds.
> 
> the `;` just programming hbits i guess 🤣
> 
> > Not sure why, but using the volume command somehow makes the container not work.
> 
> Its the checking issue with the entrypoints. it checks `if it exist`, not `if it empty`.
> 
> So when the docker image doesn't have `/opt/lib` it will work, but when mounted with volumes `/opt/lib` already exists from beginning. Then right way should be `if /opt/lib/ empty?` and dont forget create /opt/lib dir in docker image

true! i realised last night! I'll just have to find a way to check if it's empty or not that's all :)

**Comment by Macleykun** [comment]
@Dadoum wanted to check on ya if ya have had the time to play with this PR :D

**Comment by Dadoum** [comment]
Not yet (because of school) but should be able to try it out this week end if everything goes right.

**Comment by Dadoum** [comment]
LGTM, I tried it with `podman-docker` on Fedora and it just worked.

**Comment by Macleykun** [comment]
> LGTM, I tried it with `podman-docker` on Fedora and it just worked.
> 
> Still need to figure out how/where to upload it.

So you can technially merge this PR and follow this video:
https://www.youtube.com/watch?v=HwATG0ygxzU

You already have the ci/cd in place, but you need to create dockerhub account (or if you want to use the github registery, coment out the dockerhub part and uncomment the github/ghrc.io parts.

Assuming you wanna use Dockerhub.
Create an acccount and i assume you can make it under the username: dadoum

Next, you want to create a repository with the name: anisette_server

Next, you need to go into your github repo, and go into the settings, secrets and then github actions.
Create two secrets named:
DOCKERHUB_USERNAME
DOCKERHUB_TOKEN

username is your own username
but the token is the password you've set!

Once you've done that, check if actions are enabled on your repo.
The next time you commit smth to main, it'll do everything for you, and you should see a yellow or green indicator on your commits.

Clicking on it, reveals how stuff is running/completed, if you check dockerhub you should see your docker image :)

to test it out, simply use the run command but instead of using the locally build image, use the remote one!

That run command is basically what a user needs aside of installing docker to host their anisette :)

**Pull request merged**
